name: naturesociety_new
description: A new Flutter application.

version: 1.0.44+44

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_parsed_text: ^2.2.1
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4
  http: ^1.1.2
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_dynamic_links: ^6.1.5
  geolocator: ^13.0.4
  cloud_firestore: ^5.6.6
  syncfusion_flutter_sliders: ^29.1.35
  google_maps_flutter: ^2.12.1
  shared_preferences: ^2.2.2
  circularbox: ^1.1.1+1
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  photo_view: ^0.15.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.28.0
  share: ^2.0.4
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  vibration: ^3.1.3
  audioplayers: ^6.4.0
  substring_highlight: ^1.0.33
  scrollable_positioned_list: ^0.3.8
  camera: ^0.11.1
  socket_io_client: ^3.1.1
  permission_handler: ^11.1.0
  flutter_swiper_null_safety: ^1.0.2
  location: ^8.0.0
  quick_actions: ^1.0.6
  path: ^1.8.3
  flutter_google_places_sdk: ^0.4.1
  google_maps_places_autocomplete_widgets: ^1.3.3
  video_player: ^2.8.1
  dropdown_search: ^6.0.2
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  pin_code_fields: ^8.0.1
  file_picker: ^10.0.0
  flutter_datetime_picker: ^1.5.1
  flick_video_player: ^0.9.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  flutter_image_compress: ^2.1.0
  geocoding: ^3.0.0
  in_app_update: ^4.2.2
  image: ^4.5.4
  flutter_datetime_picker_plus: ^2.2.0
  google_maps_location_picker: ^3.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-Light.ttf
          style: italic

  uses-material-design: true
  assets:
    - assets/noconnection.png
    - assets/offlineMode.jpg
    - assets/natureicon.png
    - assets/message_send.mp3
    - assets/message_reply.mp3
    - assets/A.jpg
    - assets/B.jpg
    - assets/C.jpg
    - assets/D.jpg
    - assets/E.jpg
    - assets/TreeIdentifier.png
    - assets/noSearchResult.png
    - assets/loader.gif
    - assets/placeholder.png
    - assets/GetStarted/